### ISSUE TITLE
Don't use exceptions

### ISSUE THREAD

**Issue by SimonIT** [rekire/autologin_plugin#2]
In my opinion, using exceptions for saying that the user has no saved credentials is pretty bad design. It's common to use `null` for this case. This won't let my error reporting tool freak out.

Another idea is a `isSupported` method to prevent an exception raised because of a not existing Google API. This would also be very helpful with different platforms.

**Comment by rekire** [comment]
I'll check how I can improve this library.

**Comment by rekire** [comment]
I'm creating exceptions, but I do not throw it (on the Android/Kotlin side). I'm just passing them for debugging. I'm wondering where your see any thrown exceptions.

If my plugin fails to fetch the login data I'll pass the exception details by invoking `result.error(...)` for future error handling. I guess that is the place where you see exceptions on the dart side. I'll look for a solution to return null when the user has canceled the action instead of throwing an exception, which is in fact not an unexpected error.

I like the idea to add an `isSupported` property. I'll check how I can implement that without checking it twice.

**Comment by SimonIT** [comment]
I mean these lines where you catch the Platform Exception:
https://github.com/rekire/autologin_plugin/blob/44292526d884c37418dc6ae2f7f26dbd197c0b39/example/lib/main.dart#L29-L33

A Platform Exception is thrown if the user has no saved credentials (If I'm not wrong):
https://github.com/rekire/autologin_plugin/blob/44292526d884c37418dc6ae2f7f26dbd197c0b39/android/src/main/kotlin/eu/rekisoft/flutter/autologin/LoginHelper.kt#L33-L37
https://github.com/rekire/autologin_plugin/blob/44292526d884c37418dc6ae2f7f26dbd197c0b39/android/src/main/kotlin/eu/rekisoft/flutter/autologin/LoginHelper.kt#L50-L54
That's where I expected the returned null value instead of an exception because it's a quiet normal to not have saved credentials.

A Platform Exception is also a pretty general exception. So if anything else goes wrong the Platform Exception gets catched and no one gets informed about the problem. A workaround for this would be parsing the exception message, but it's more complicated than it could be. I suggest null as return value or create a special exception inside dart so only this "error" can get catched.

Then I got this exception because of a not existing google account which I would avoid with a `isSupported` method:
```
PlatformException(16, Error code 16 while loading the login data (16: No eligible accounts can be found.), eu.rekisoft.flutter.autologin.LoginHelper$GoogleApiError: Error code 16 while loading the login data (16: No eligible accounts can be found.)
	at eu.rekisoft.flutter.autologin.LoginHelper$loadLoginData$1.onComplete(LoginHelper.kt:64)
	at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: com.google.android.gms.common.api.ApiException: 16: No eligible accounts can be found.
	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
	at com.google.android.gms.common.internal.zai.zaf(com.google.android.gms:play-services-base@@17.1.0:2)
	at com.google.android.gms.common.internal.zak.onComplete(com.google.android.gms:play-services-base@@17.1.0:6)
	at com.google.android.gms.common.api.internal.BasePendingResult.zaa(com.google.android.gms:play-services-base@@17.1.0:176)
	at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@17.1.0:135)
	at com.google.android.gms.internal.auth-api.zzl.zzc(com.google.android.gms:play-services-auth@@18.0.0:2)
	at com.google.android.gms.internal.auth-api.zzu.dispatchTransaction(com.google.android.gms:play-services-auth@@18.0.0:6)
	at com.google.android.gms.internal.auth-api.zzc.onTransact(com.google.android.gms:play-services-auth@@18.0.0:13)
	at android.os.Binder.execTransact(Binder.java:731)
)
```
I would also add the availability check you already have to the `isSupported` method.
https://github.com/rekire/autologin_plugin/blob/44292526d884c37418dc6ae2f7f26dbd197c0b39/android/src/main/kotlin/eu/rekisoft/flutter/autologin/LoginHelper.kt#L23
